services:
  - type: web
    name: flask-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-db
          property: connectionString

databases:
  - name: flask-db
